BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*.bb"
BBFILE_COLLECTIONS += "core"
BBFILE_PATTERN_core = "^${LAYERDIR}/"
LAYERSERIES_CORENAMES = "sop"
BBFILE_PRIORITY_core = "5"
LAYERSERIES_COMPAT_core = "sop"
